# Numpy

In [10]:
#1.Write a numpy program to convert angles from degree to radian for all elements in given array.
import numpy as np
np.deg2rad(30),np.sin(0.5235987755982988)

(0.5235987755982988, 0.49999999999999994)

In [11]:
#2.How to reverse the rows of a 2D array?
#[[6, 7, 8],
# [3, 4, 5],
# [0, 1, 2]]
arr = [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
reversed_arr = [list(reversed(row)) for row in arr]
print(reversed_arr)

[[8, 7, 6], [5, 4, 3], [2, 1, 0]]


In [12]:
#3.Create a 3x3x3 array with random values.
arr = np.random.rand(3, 3, 3)
print(arr)

[[[0.72962702 0.12257178 0.38872805]
  [0.54399969 0.52086532 0.74704685]
  [0.78386703 0.68766084 0.71794446]]

 [[0.41694167 0.63999287 0.01519707]
  [0.64595702 0.55241092 0.4741403 ]
  [0.86657585 0.49208224 0.95799268]]

 [[0.40269264 0.97068556 0.67430956]
  [0.98088015 0.29915475 0.58747184]
  [0.47997896 0.73331088 0.70316729]]]


In [13]:
#4.Create a 2d array with 1 on the border and 0 inside.
"""[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]  8,e=0
[1. 0. 0. 0. 9. 9. e. 8. 9. 1.] 
[1. e. e. e. e. a. e. e. 8. 1.]
[1. 8. e. e. 8. 9. e. e. e. 1.] 
[1, 0, 0.0, 0. e. e. e. e. 1.] 
[1. e. e. e. e. e. e. e. e. 1.] 
[1. e. 0, 0, 0, 0, 0. e. e. 1.]
[1, 0. 0. 8. e. e. o. e. e. 1.] 
[1. e. e. e. 3. e. 8. e. e. 1.] 
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]"""
 
nrows = 10
ncols = 10
arr = np.zeros((nrows, ncols))
arr[0, :] = 1
arr[-1, :] = 1
arr[:, 0] = 1
arr[:, -1] = 1
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [14]:
#5.Write a NumPy program to compute the inverse of a given matrix.
a=np.array([[3,4],[5,6]])
print(a)
np.linalg.inv(a)

[[3 4]
 [5 6]]


array([[-3. ,  2. ],
       [ 2.5, -1.5]])

In [15]:
#6.How to swap two rows of an array with practically.
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Input array:")
print(a)
temp = a[1].copy()
a[1] = a[2]
a[2] = temp
print("Output array:")
print(a)


Input array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Output array:
[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [24]:
#7.How to find the most frequent value in a NumPy array with practically.
a = np.array([1, 2, 3, 2, 2, 1, 3, 3, 3])
np.argmax(a)

a = np.array([1, 2, 3, 2, 2, 3, 4, 4, 4, 4, 3, 3, 3, 5])
counts = np.bincount(a)
most_frequent_value = np.argmax(counts)
print("The most frequent value is:", most_frequent_value)

The most frequent value is: 3


In [8]:
#8.How to compute the standard deviation of a NumPy array.
a=np.array([1,2,3,4,5])
np.std(a)

1.4142135623730951

In [26]:
#9.How to sort an array by the nth column with practically.
a = np.array([[1, 4], [2, 3], [3, 2], [4, 1]])
n = 1
sorted_indices = np.argsort(a[:, n])
sorted_a = a[sorted_indices]
print("The sorted array is:")
print(sorted_arr)

The sorted array is:
[[4 1]
 [3 2]
 [2 3]
 [1 4]]


In [31]:
#10.Create a random vector of size 10 and sort it.
a = np.random.rand(10)
sorted_vector= np.sort(a)
print(sorted_vector)

[0.01299039 0.07564117 0.18858684 0.37371088 0.37739874 0.3984117
 0.44224716 0.61791529 0.95154488 0.97888727]


# Pandas

In [61]:
#1.What are the different ways of creating DataFrame in pandas? Explain with examples.
import pandas as pd

#1.Creating from a dictionary:
data = {'col1': [1,2,3], 'col2': [4,5,6], 'col3': [7,8,9]}
df = pd.DataFrame(data)
print(df)

#2.Creating from a list of dictionaries:
a=[{'a':[1,2,3,4,5]},{'b':'Reshma'}]
pd.DataFrame(a)
print(a)

#3.Creating from a NumPy array:
data = np.array([['John', 25, 'USA'],
                 ['Jane', 30, 'Canada'],
                 ['Bob', 40, 'UK'],
                 ['Sue', 35, 'Australia']])
df = pd.DataFrame(data, columns=['Name', 'Age', 'Country'])
print(df)

#4.Creating from a CSV file:
df = pd.read_csv('Iris .csv')
print(df)

#5.Using Series:
s1=pd.series(['a','b','c'])
s2=pd.series([10,20,30])
a1=pd.DataFrame({'A':s1,'B':s2})
print(a1)

   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6     9
[{'a': [1, 2, 3, 4, 5]}, {'b': 'Reshma'}]
   Name Age    Country
0  John  25        USA
1  Jane  30     Canada
2   Bob  40         UK
3   Sue  35  Australia


In [ ]:
#2.What is Groupby Function In Pandas? Explain with example.

In [46]:
#3.What Method Will You Use To Rename The Index Or Columns Of Pandas Dataframe.
df=pd.DataFrame({'A':np.random.randint(10,20,5),'B':[10,20,30,40,50]})
print(df)

df.rename({'A':'a','B':'b'},axis=1,inplace=True)
df

    A   B
0  15  10
1  15  20
2  17  30
3  19  40
4  16  50


a   b
0  15  10
1  15  20
2  17  30
3  19  40
4  16  50

# Machine Learning