# Logistic Regression :

In [125]:
#Import all libraries
import pandas as pd
import numpy as np
import seaborn as sns
#Train test split
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
#Accruacy score
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,precision_score

In [148]:
#Load dataset
data=sns.load_dataset('iris')
data.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [149]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [150]:
data['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [151]:
data.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [152]:
data=data[data['species']!='setosa']

In [153]:
data['species']=data['species'].map({'versicolor':0, 'virginica':1})

In [154]:
data['species'].unique()

array([0, 1], dtype=int64)

In [155]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100 entries, 50 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  100 non-null    float64
 1   sepal_width   100 non-null    float64
 2   petal_length  100 non-null    float64
 3   petal_width   100 non-null    float64
 4   species       100 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 4.7 KB


In [156]:
#Split my data set into independent and dependent data.
y=data['species']
x=data.drop('species',axis=1)
x

sepal_length  sepal_width  petal_length  petal_width
50            7.0          3.2           4.7          1.4
51            6.4          3.2           4.5          1.5
52            6.9          3.1           4.9          1.5
53            5.5          2.3           4.0          1.3
54            6.5          2.8           4.6          1.5
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[100 rows x 4 columns]

In [158]:
x,y

(     sepal_length  sepal_width  petal_length  petal_width
 50            7.0          3.2           4.7          1.4
 51            6.4          3.2           4.5          1.5
 52            6.9          3.1           4.9          1.5
 53            5.5          2.3           4.0          1.3
 54            6.5          2.8           4.6          1.5
 ..            ...          ...           ...          ...
 145           6.7          3.0           5.2          2.3
 146           6.3          2.5           5.0          1.9
 147           6.5          3.0           5.2          2.0
 148           6.2          3.4           5.4          2.3
 149           5.9          3.0           5.1          1.8
 
 [100 rows x 4 columns],
 50     0
 51     0
 52     0
 53     0
 54     0
       ..
 145    1
 146    1
 147    1
 148    1
 149    1
 Name: species, Length: 100, dtype: int64)

In [159]:
#train test split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=54)

In [160]:
x_train

sepal_length  sepal_width  petal_length  petal_width
97            6.2          2.9           4.3          1.3
70            5.9          3.2           4.8          1.8
54            6.5          2.8           4.6          1.5
115           6.4          3.2           5.3          2.3
126           6.2          2.8           4.8          1.8
..            ...          ...           ...          ...
114           5.8          2.8           5.1          2.4
73            6.1          2.8           4.7          1.2
65            6.7          3.1           4.4          1.4
52            6.9          3.1           4.9          1.5
119           6.0          2.2           5.0          1.5

[70 rows x 4 columns]

In [161]:
x_test

sepal_length  sepal_width  petal_length  petal_width
86            6.7          3.1           4.7          1.5
120           6.9          3.2           5.7          2.3
98            5.1          2.5           3.0          1.1
144           6.7          3.3           5.7          2.5
131           7.9          3.8           6.4          2.0
96            5.7          2.9           4.2          1.3
88            5.6          3.0           4.1          1.3
79            5.7          2.6           3.5          1.0
84            5.4          3.0           4.5          1.5
72            6.3          2.5           4.9          1.5
135           7.7          3.0           6.1          2.3
142           5.8          2.7           5.1          1.9
141           6.9          3.1           5.1          2.3
82            5.8          2.7           3.9          1.2
50            7.0          3.2           4.7          1.4
60            5.0          2.0           3.5          1.0
145           6.7          3.0           5.2          2.3
117           7.7          3.8           6.7          2.2
109           7.2          3.6           6.1          2.5
83            6.0          2.7           5.1          1.6
140           6.7          3.1           5.6          2.4
81            5.5          2.4           3.7          1.0
108           6.7          2.5           5.8          1.8
124           6.7          3.3           5.7          2.1
139           6.9          3.1           5.4          2.1
147           6.5          3.0           5.2          2.0
133           6.3          2.8           5.1          1.5
61            5.9          3.0           4.2          1.5
111           6.4          2.7           5.3          1.9
138           6.0          3.0           4.8          1.8

In [162]:
classifier=LogisticRegression()
classifier

LogisticRegression()

In [163]:
classifier.fit(x_train,y_train)

LogisticRegression()

In [164]:
#Accuracy of Testing data
y_pred=classifier.predict(x_test)
y_pred

array([0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1], dtype=int64)

In [165]:
y_test

86     0
120    1
98     0
144    1
131    1
96     0
88     0
79     0
84     0
72     0
135    1
142    1
141    1
82     0
50     0
60     0
145    1
117    1
109    1
83     0
140    1
81     0
108    1
124    1
139    1
147    1
133    1
61     0
111    1
138    1
Name: species, dtype: int64

In [167]:
y_test-y_pred

86     0
120    0
98     0
144    0
131    0
96     0
88     0
79     0
84     0
72     0
135    0
142    0
141    0
82     0
50     0
60     0
145    0
117    0
109    0
83    -1
140    0
81     0
108    0
124    0
139    0
147    0
133    0
61     0
111    0
138    0
Name: species, dtype: int64

In [192]:
score=accuracy_score(y_pred,y_test)

In [193]:
score*100

96.66666666666667

In [194]:
#Accuracy of Training data
y_pred_train=classifier.predict(x_train)
y_pred_train

array([0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1], dtype=int64)

# Model Evaluations :

In [195]:
train_score=accuracy_score(y_pred_train,y_train)
train_score

0.9714285714285714

In [196]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.92      1.00      0.96        12
           1       1.00      0.94      0.97        18

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [197]:
print(classification_report(y_pred_train,y_train))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97        37
           1       0.97      0.97      0.97        33

    accuracy                           0.97        70
   macro avg       0.97      0.97      0.97        70
weighted avg       0.97      0.97      0.97        70



In [198]:
confusion_matrix(y_pred,y_test)

array([[12,  0],
       [ 1, 17]], dtype=int64)

In [199]:
confusion_matrix(y_pred_train,y_train)

array([[36,  1],
       [ 1, 32]], dtype=int64)

In [200]:
precision=(11/12)
precision

0.9166666666666666

In [201]:
precision_score(y_pred,y_test)

1.0