Null Value Treatments :

In [1]:
import pandas as pd

In [16]:
data=pd.read_csv('Emp_Records.csv')
data

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0   677509       Lois       36.36            NaN           13.68  168251   
1   940761     Brenda       47.02            NaN             NaN   51063   
2   428945        Joe       54.15           68.0            0.98   50155   
3   408351      Diane       39.67            NaN           18.30  180294   
4   193819   Benjamin       40.31           58.0            4.01  117642   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82           89.0            1.05  129774   
96  704709     Harold       32.61           77.0            5.93  156194   
97  461593     Nicole       52.66           60.0           28.53   95673   
98  392491    Theresa       29.60           57.0            6.99   51015   
99  495141      Tammy       38.38           55.0            2.26   93650   

            City  
0            NaN  
1      Stonewall  
2   Michigantown  
3       Hydetown  
4        Fremont  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[100 rows x 7 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Emp ID          100 non-null    int64  
 1   First Name      100 non-null    object 
 2   Age in Yrs      100 non-null    float64
 3   Weight in Kgs   97 non-null     float64
 4   Age in Company  99 non-null     float64
 5   Salary          100 non-null    int64  
 6   City            99 non-null     object 
dtypes: float64(3), int64(2), object(2)
memory usage: 5.6+ KB


isna() :
  The isna() method return a DataFrame object where all the values are replaced with a boolean value True for NA
  (Not A Number) values and, otherwise False.
 Syntax :
   dataframe.isna()
     PARAMETER --> This method takes no parameter.
     RETURN VALUE --> Returns A DataFrame with boolean values.

In [5]:
data.isna()

Emp ID  First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0    False       False       False           True           False   False   
1    False       False       False           True            True   False   
2    False       False       False          False           False   False   
3    False       False       False           True           False   False   
4    False       False       False          False           False   False   
..     ...         ...         ...            ...             ...     ...   
95   False       False       False          False           False   False   
96   False       False       False          False           False   False   
97   False       False       False          False           False   False   
98   False       False       False          False           False   False   
99   False       False       False          False           False   False   

     City  
0    True  
1   False  
2   False  
3   False  
4   False  
..    ...  
95  False  
96  False  
97  False  
98  False  
99  False  

[100 rows x 7 columns]

In [6]:
data.isna().sum()   

Emp ID            0
First Name        0
Age in Yrs        0
Weight in Kgs     3
Age in Company    1
Salary            0
City              1
dtype: int64

In [7]:
data.isnull().sum()

Emp ID            0
First Name        0
Age in Yrs        0
Weight in Kgs     3
Age in Company    1
Salary            0
City              1
dtype: int64

dropna() :
  The dropna() method remove the rows that contains null values.
  The dropna() method return a new dataframe object unless the inplace parameter is set to true.

In [8]:
data.dropna()

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
2   428945        Joe       54.15           68.0            0.98   50155   
4   193819   Benjamin       40.31           58.0            4.01  117642   
5   499687    Patrick       34.86           58.0           12.02   72305   
6   539712      Nancy       22.14           50.0            0.87   98189   
7   380086      Carol       59.12           40.0           34.52   60918   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82           89.0            1.05  129774   
96  704709     Harold       32.61           77.0            5.93  156194   
97  461593     Nicole       52.66           60.0           28.53   95673   
98  392491    Theresa       29.60           57.0            6.99   51015   
99  495141      Tammy       38.38           55.0            2.26   93650   

            City  
2   Michigantown  
4        Fremont  
5      Macksburg  
6        Atlanta  
7    Blanchester  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[97 rows x 7 columns]

In [13]:
#data=data.dropna()    #Assign Method
data

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0   677509       Lois       36.36            NaN           13.68  168251   
1   940761     Brenda       47.02            NaN             NaN   51063   
2   428945        Joe       54.15           68.0            0.98   50155   
3   408351      Diane       39.67            NaN           18.30  180294   
4   193819   Benjamin       40.31           58.0            4.01  117642   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82           89.0            1.05  129774   
96  704709     Harold       32.61           77.0            5.93  156194   
97  461593     Nicole       52.66           60.0           28.53   95673   
98  392491    Theresa       29.60           57.0            6.99   51015   
99  495141      Tammy       38.38           55.0            2.26   93650   

            City  
0            NaN  
1      Stonewall  
2   Michigantown  
3       Hydetown  
4        Fremont  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[100 rows x 7 columns]

In [15]:
data.dropna(inplace=True)
data

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
2   428945        Joe       54.15           68.0            0.98   50155   
4   193819   Benjamin       40.31           58.0            4.01  117642   
5   499687    Patrick       34.86           58.0           12.02   72305   
6   539712      Nancy       22.14           50.0            0.87   98189   
7   380086      Carol       59.12           40.0           34.52   60918   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82           89.0            1.05  129774   
96  704709     Harold       32.61           77.0            5.93  156194   
97  461593     Nicole       52.66           60.0           28.53   95673   
98  392491    Theresa       29.60           57.0            6.99   51015   
99  495141      Tammy       38.38           55.0            2.26   93650   

            City  
2   Michigantown  
4        Fremont  
5      Macksburg  
6        Atlanta  
7    Blanchester  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[97 rows x 7 columns]

Thresold Paramter With Axis() :
  Atleast n columns should have non null value.
          Axis=0--> Along rowwise it iterate column.
          Axis=1--> Along columnwise it iterate row.

In [20]:
data.dropna(thresh=6,axis=0)    #Columns--> Rows Delete

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
2   428945        Joe       54.15           68.0            0.98   50155   
3   408351      Diane       39.67            NaN           18.30  180294   
4   193819   Benjamin       40.31           58.0            4.01  117642   
5   499687    Patrick       34.86           58.0           12.02   72305   
6   539712      Nancy       22.14           50.0            0.87   98189   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82           89.0            1.05  129774   
96  704709     Harold       32.61           77.0            5.93  156194   
97  461593     Nicole       52.66           60.0           28.53   95673   
98  392491    Theresa       29.60           57.0            6.99   51015   
99  495141      Tammy       38.38           55.0            2.26   93650   

            City  
2   Michigantown  
3       Hydetown  
4        Fremont  
5      Macksburg  
6        Atlanta  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[98 rows x 7 columns]

In [19]:
data.dropna(thresh=99,axis=1)    #Rows--> Columns Delete

Emp ID First Name  Age in Yrs  Age in Company  Salary          City
0   677509       Lois       36.36           13.68  168251           NaN
1   940761     Brenda       47.02             NaN   51063     Stonewall
2   428945        Joe       54.15            0.98   50155  Michigantown
3   408351      Diane       39.67           18.30  180294      Hydetown
4   193819   Benjamin       40.31            4.01  117642       Fremont
..     ...        ...         ...             ...     ...           ...
95  639892       Jose       22.82            1.05  129774        Biloxi
96  704709     Harold       32.61            5.93  156194  Carol Stream
97  461593     Nicole       52.66           28.53   95673       Detroit
98  392491    Theresa       29.60            6.99   51015      Mc Grath
99  495141      Tammy       38.38            2.26   93650          Alma

[100 rows x 6 columns]

Subset Parameter() :
  With the help of given column in this column null value present then entire row will be delete.

In [25]:
data.dropna(subset='Weight in Kgs')

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
2   428945        Joe       54.15           68.0            0.98   50155   
4   193819   Benjamin       40.31           58.0            4.01  117642   
5   499687    Patrick       34.86           58.0           12.02   72305   
6   539712      Nancy       22.14           50.0            0.87   98189   
7   380086      Carol       59.12           40.0           34.52   60918   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82           89.0            1.05  129774   
96  704709     Harold       32.61           77.0            5.93  156194   
97  461593     Nicole       52.66           60.0           28.53   95673   
98  392491    Theresa       29.60           57.0            6.99   51015   
99  495141      Tammy       38.38           55.0            2.26   93650   

            City  
2   Michigantown  
4        Fremont  
5      Macksburg  
6        Atlanta  
7    Blanchester  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[97 rows x 7 columns]

In [26]:
data

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0   677509       Lois       36.36            NaN           13.68  168251   
1   940761     Brenda       47.02            NaN             NaN   51063   
2   428945        Joe       54.15           68.0            0.98   50155   
3   408351      Diane       39.67            NaN           18.30  180294   
4   193819   Benjamin       40.31           58.0            4.01  117642   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82           89.0            1.05  129774   
96  704709     Harold       32.61           77.0            5.93  156194   
97  461593     Nicole       52.66           60.0           28.53   95673   
98  392491    Theresa       29.60           57.0            6.99   51015   
99  495141      Tammy       38.38           55.0            2.26   93650   

            City  
0            NaN  
1      Stonewall  
2   Michigantown  
3       Hydetown  
4        Fremont  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[100 rows x 7 columns]

In [27]:
data.dropna(subset=['Weight in Kgs','City'])

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
2   428945        Joe       54.15           68.0            0.98   50155   
4   193819   Benjamin       40.31           58.0            4.01  117642   
5   499687    Patrick       34.86           58.0           12.02   72305   
6   539712      Nancy       22.14           50.0            0.87   98189   
7   380086      Carol       59.12           40.0           34.52   60918   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82           89.0            1.05  129774   
96  704709     Harold       32.61           77.0            5.93  156194   
97  461593     Nicole       52.66           60.0           28.53   95673   
98  392491    Theresa       29.60           57.0            6.99   51015   
99  495141      Tammy       38.38           55.0            2.26   93650   

            City  
2   Michigantown  
4        Fremont  
5      Macksburg  
6        Atlanta  
7    Blanchester  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[97 rows x 7 columns]

Subset How Any And All Function :
 By default --> how 'any' ==> Any one features (from fist column).
 By defalut --> how 'all' ==> All features.

In [32]:
data.head()

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0  677509       Lois       36.36            NaN           13.68  168251   
1  940761     Brenda       47.02            NaN             NaN   51063   
2  428945        Joe       54.15           68.0            0.98   50155   
3  408351      Diane       39.67            NaN           18.30  180294   
4  193819   Benjamin       40.31           58.0            4.01  117642   

           City  
0           NaN  
1     Stonewall  
2  Michigantown  
3      Hydetown  
4       Fremont

In [31]:
data.dropna(subset=['Weight in Kgs','Age in Company'],how='any')  #Any

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
2   428945        Joe       54.15           68.0            0.98   50155   
4   193819   Benjamin       40.31           58.0            4.01  117642   
5   499687    Patrick       34.86           58.0           12.02   72305   
6   539712      Nancy       22.14           50.0            0.87   98189   
7   380086      Carol       59.12           40.0           34.52   60918   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82           89.0            1.05  129774   
96  704709     Harold       32.61           77.0            5.93  156194   
97  461593     Nicole       52.66           60.0           28.53   95673   
98  392491    Theresa       29.60           57.0            6.99   51015   
99  495141      Tammy       38.38           55.0            2.26   93650   

            City  
2   Michigantown  
4        Fremont  
5      Macksburg  
6        Atlanta  
7    Blanchester  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[97 rows x 7 columns]

In [33]:
data.dropna(subset=['Weight in Kgs','Age in Company'],how='all')  #All

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0   677509       Lois       36.36            NaN           13.68  168251   
2   428945        Joe       54.15           68.0            0.98   50155   
3   408351      Diane       39.67            NaN           18.30  180294   
4   193819   Benjamin       40.31           58.0            4.01  117642   
5   499687    Patrick       34.86           58.0           12.02   72305   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82           89.0            1.05  129774   
96  704709     Harold       32.61           77.0            5.93  156194   
97  461593     Nicole       52.66           60.0           28.53   95673   
98  392491    Theresa       29.60           57.0            6.99   51015   
99  495141      Tammy       38.38           55.0            2.26   93650   

            City  
0            NaN  
2   Michigantown  
3       Hydetown  
4        Fremont  
5      Macksburg  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[99 rows x 7 columns]

In [38]:
np.where(data['Weight in Kgs'].isna())   #Find the index=np.where()

(array([0, 1, 3], dtype=int64),)

In [40]:
data['Weight in Kgs']

0      NaN
1      NaN
2     68.0
3      NaN
4     58.0
      ... 
95    89.0
96    77.0
97    60.0
98    57.0
99    55.0
Name: Weight in Kgs, Length: 100, dtype: float64

In [39]:
np.where(data['Weight in Kgs']>50)

(array([ 2,  4,  5,  9, 10, 11, 12, 13, 16, 17, 18, 19, 20, 21, 22, 23, 24,
        25, 26, 27, 31, 32, 33, 34, 35, 36, 37, 38, 43, 44, 45, 46, 48, 50,
        52, 53, 54, 59, 61, 62, 63, 64, 65, 66, 67, 68, 70, 71, 72, 73, 74,
        77, 79, 81, 82, 83, 84, 85, 86, 87, 89, 90, 91, 92, 93, 94, 95, 96,
        97, 98, 99], dtype=int64),)

In [41]:
np.where(data['Weight in Kgs']==89.0)

(array([95], dtype=int64),)

Dropping Selected row and column :

Dropping Cloumns :

In [8]:
data=pd.read_csv('Emp_Records.csv')
data

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0   677509       Lois       36.36            NaN           13.68  168251   
1   940761     Brenda       47.02            NaN             NaN   51063   
2   428945        Joe       54.15           68.0            0.98   50155   
3   408351      Diane       39.67            NaN           18.30  180294   
4   193819   Benjamin       40.31           58.0            4.01  117642   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82           89.0            1.05  129774   
96  704709     Harold       32.61           77.0            5.93  156194   
97  461593     Nicole       52.66           60.0           28.53   95673   
98  392491    Theresa       29.60           57.0            6.99   51015   
99  495141      Tammy       38.38           55.0            2.26   93650   

            City  
0            NaN  
1      Stonewall  
2   Michigantown  
3       Hydetown  
4        Fremont  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[100 rows x 7 columns]

In [3]:
data.drop('First Name',axis=1,inplace=True)

In [4]:
data

Emp ID  Age in Yrs  Weight in Kgs  Age in Company  Salary          City
0   677509       36.36            NaN           13.68  168251           NaN
1   940761       47.02            NaN             NaN   51063     Stonewall
2   428945       54.15           68.0            0.98   50155  Michigantown
3   408351       39.67            NaN           18.30  180294      Hydetown
4   193819       40.31           58.0            4.01  117642       Fremont
..     ...         ...            ...             ...     ...           ...
95  639892       22.82           89.0            1.05  129774        Biloxi
96  704709       32.61           77.0            5.93  156194  Carol Stream
97  461593       52.66           60.0           28.53   95673       Detroit
98  392491       29.60           57.0            6.99   51015      Mc Grath
99  495141       38.38           55.0            2.26   93650          Alma

[100 rows x 6 columns]

In [7]:
data.drop(['Salary','City'],axis=True,inplace=True)
data

Emp ID  Age in Yrs  Weight in Kgs  Age in Company
0   677509       36.36            NaN           13.68
1   940761       47.02            NaN             NaN
2   428945       54.15           68.0            0.98
3   408351       39.67            NaN           18.30
4   193819       40.31           58.0            4.01
..     ...         ...            ...             ...
95  639892       22.82           89.0            1.05
96  704709       32.61           77.0            5.93
97  461593       52.66           60.0           28.53
98  392491       29.60           57.0            6.99
99  495141       38.38           55.0            2.26

[100 rows x 4 columns]

Dropping Rows :

In [9]:
data

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0   677509       Lois       36.36            NaN           13.68  168251   
1   940761     Brenda       47.02            NaN             NaN   51063   
2   428945        Joe       54.15           68.0            0.98   50155   
3   408351      Diane       39.67            NaN           18.30  180294   
4   193819   Benjamin       40.31           58.0            4.01  117642   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82           89.0            1.05  129774   
96  704709     Harold       32.61           77.0            5.93  156194   
97  461593     Nicole       52.66           60.0           28.53   95673   
98  392491    Theresa       29.60           57.0            6.99   51015   
99  495141      Tammy       38.38           55.0            2.26   93650   

            City  
0            NaN  
1      Stonewall  
2   Michigantown  
3       Hydetown  
4        Fremont  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[100 rows x 7 columns]

In [13]:
data.drop(0,axis=0)

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
1   940761     Brenda       47.02            NaN             NaN   51063   
2   428945        Joe       54.15           68.0            0.98   50155   
3   408351      Diane       39.67            NaN           18.30  180294   
4   193819   Benjamin       40.31           58.0            4.01  117642   
5   499687    Patrick       34.86           58.0           12.02   72305   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82           89.0            1.05  129774   
96  704709     Harold       32.61           77.0            5.93  156194   
97  461593     Nicole       52.66           60.0           28.53   95673   
98  392491    Theresa       29.60           57.0            6.99   51015   
99  495141      Tammy       38.38           55.0            2.26   93650   

            City  
1      Stonewall  
2   Michigantown  
3       Hydetown  
4        Fremont  
5      Macksburg  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[99 rows x 7 columns]

In [14]:
data.drop([0,1],axis=0)

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
2   428945        Joe       54.15           68.0            0.98   50155   
3   408351      Diane       39.67            NaN           18.30  180294   
4   193819   Benjamin       40.31           58.0            4.01  117642   
5   499687    Patrick       34.86           58.0           12.02   72305   
6   539712      Nancy       22.14           50.0            0.87   98189   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82           89.0            1.05  129774   
96  704709     Harold       32.61           77.0            5.93  156194   
97  461593     Nicole       52.66           60.0           28.53   95673   
98  392491    Theresa       29.60           57.0            6.99   51015   
99  495141      Tammy       38.38           55.0            2.26   93650   

            City  
2   Michigantown  
3       Hydetown  
4        Fremont  
5      Macksburg  
6        Atlanta  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[98 rows x 7 columns]

In [17]:
import numpy as np

In [18]:
np.where(data['Salary']>50000)  

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 25, 26, 27, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        73, 74, 75, 76, 77, 78, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99], dtype=int64),)

In [28]:
data.loc[data['Salary']>50000]

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0   677509       Lois       36.36            NaN           13.68  168251   
1   940761     Brenda       47.02            NaN             NaN   51063   
2   428945        Joe       54.15           68.0            0.98   50155   
3   408351      Diane       39.67            NaN           18.30  180294   
4   193819   Benjamin       40.31           58.0            4.01  117642   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82           89.0            1.05  129774   
96  704709     Harold       32.61           77.0            5.93  156194   
97  461593     Nicole       52.66           60.0           28.53   95673   
98  392491    Theresa       29.60           57.0            6.99   51015   
99  495141      Tammy       38.38           55.0            2.26   93650   

            City  
0            NaN  
1      Stonewall  
2   Michigantown  
3       Hydetown  
4        Fremont  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[94 rows x 7 columns]

In [26]:
[data['Salary']>50000]

[0     True
 1     True
 2     True
 3     True
 4     True
       ... 
 95    True
 96    True
 97    True
 98    True
 99    True
 Name: Salary, Length: 100, dtype: bool]

In [31]:
[[data['Salary']>50000] and [data['Salary']<60000]]

[[0     False
  1      True
  2      True
  3     False
  4     False
        ...  
  95    False
  96    False
  97    False
  98     True
  99    False
  Name: Salary, Length: 100, dtype: bool]]

In [32]:
np.where([data['Salary']>50000] and [data['Salary']<60000])

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64),
 array([ 1,  2,  9, 21, 24, 28, 36, 60, 66, 72, 79, 86, 91, 98],
       dtype=int64))

In [48]:
data.iloc[:][[data['Salary']>50000] and data['Salary']<60000]   

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
1   940761     Brenda       47.02            NaN             NaN   51063   
2   428945        Joe       54.15           68.0            0.98   50155   
9   162402      Diana       29.73           60.0            3.44   43010   
21  969580    Matthew       23.77           56.0            1.47   52237   
24  560455    Carolyn       59.42           53.0           16.08   42005   
28  474599      Maria       42.39           41.0           18.84   48944   
36  218791      Aaron       48.49           56.0           20.08   54402   
60  687017    Frances       56.53           42.0            6.94   46945   
66  183071     Andrea       32.08           52.0            7.28   54179   
72  951225   Margaret       25.10           56.0            0.92   43867   
79  325319    Carolyn       41.19           60.0            2.73   48736   
86  533952      Kelly       42.21           53.0            4.07   51878   
91  867084    Deborah       39.77           54.0           15.41   52767   
98  392491    Theresa       29.60           57.0            6.99   51015   

              City  
1        Stonewall  
2     Michigantown  
9   Eureka Springs  
21     Heathsville  
24     Saint Cloud  
28    Lawrenceburg  
36         Eckerty  
60           Trego  
66         Granger  
72         Haswell  
79         Wheaton  
86            Meno  
91         Atqasuk  
98        Mc Grath

In [50]:
data.iloc[:][(data['Salary']>50000) & (data['Salary']<60000)]    #[:]-->All row indexing 

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
1   940761     Brenda       47.02            NaN             NaN   51063   
2   428945        Joe       54.15           68.0            0.98   50155   
21  969580    Matthew       23.77           56.0            1.47   52237   
36  218791      Aaron       48.49           56.0           20.08   54402   
66  183071     Andrea       32.08           52.0            7.28   54179   
86  533952      Kelly       42.21           53.0            4.07   51878   
91  867084    Deborah       39.77           54.0           15.41   52767   
98  392491    Theresa       29.60           57.0            6.99   51015   

            City  
1      Stonewall  
2   Michigantown  
21   Heathsville  
36       Eckerty  
66       Granger  
86          Meno  
91       Atqasuk  
98      Mc Grath

In [70]:
data['Weight in Kgs'].isnull() & data['Age in Company'].isnull()

0     False
1      True
2     False
3     False
4     False
      ...  
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool

In [69]:
data.drop(data.loc[data['Weight in Kgs'].isnull() & data['Age in Company'].isnull()].index,axis=0)

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0   677509       Lois       36.36            NaN           13.68  168251   
2   428945        Joe       54.15           68.0            0.98   50155   
3   408351      Diane       39.67            NaN           18.30  180294   
4   193819   Benjamin       40.31           58.0            4.01  117642   
5   499687    Patrick       34.86           58.0           12.02   72305   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82           89.0            1.05  129774   
96  704709     Harold       32.61           77.0            5.93  156194   
97  461593     Nicole       52.66           60.0           28.53   95673   
98  392491    Theresa       29.60           57.0            6.99   51015   
99  495141      Tammy       38.38           55.0            2.26   93650   

            City  
0            NaN  
2   Michigantown  
3       Hydetown  
4        Fremont  
5      Macksburg  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[99 rows x 7 columns]

In [73]:
data.dropna(subset=['Weight in Kgs','Age in Company'],axis=0,how='all')  #Delete all data in both kgs and age isn null(NaN)

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0   677509       Lois       36.36            NaN           13.68  168251   
2   428945        Joe       54.15           68.0            0.98   50155   
3   408351      Diane       39.67            NaN           18.30  180294   
4   193819   Benjamin       40.31           58.0            4.01  117642   
5   499687    Patrick       34.86           58.0           12.02   72305   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82           89.0            1.05  129774   
96  704709     Harold       32.61           77.0            5.93  156194   
97  461593     Nicole       52.66           60.0           28.53   95673   
98  392491    Theresa       29.60           57.0            6.99   51015   
99  495141      Tammy       38.38           55.0            2.26   93650   

            City  
0            NaN  
2   Michigantown  
3       Hydetown  
4        Fremont  
5      Macksburg  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[99 rows x 7 columns]

Finding The index having null value for any particular columns :

In [74]:
np.where(data['Weight in Kgs'].isnull())

(array([0, 1, 3], dtype=int64),)

In [76]:
data.loc[data['Weight in Kgs'].isnull()]

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0  677509       Lois       36.36            NaN           13.68  168251   
1  940761     Brenda       47.02            NaN             NaN   51063   
3  408351      Diane       39.67            NaN           18.30  180294   

        City  
0        NaN  
1  Stonewall  
3   Hydetown

In [77]:
data.loc[data['Weight in Kgs'].isnull()].index

Int64Index([0, 1, 3], dtype='int64')

In [75]:
np.where(data['Age in Company'].isnull())

(array([1], dtype=int64),)

In [78]:
data.loc[data['Age in Company'].isnull()]

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
1  940761     Brenda       47.02            NaN             NaN   51063   

        City  
1  Stonewall

In [79]:
data.loc[data['Age in Company'].isnull()].index

Int64Index([1], dtype='int64')

Dropping Null values :
 Counting the Null values in columns or checking the position having null values.
  df.isnull() --> Checking Null Values.
  df.isna() --> Checking Null Values.
  
  df.isnull().sum() --> Counting Null Values.
  df.isna().sum() --> Counting Null Values.

 Dropping The Values : 
  1.df.dropna(thresh=number,subset=[column set],axis={True/False},inplace={True/False},how={any/all}
  
  2.df.drop() --> Dropping Selected the rows and columns. 
    df.drop(df.loc[(data['column_name'].isnull()) Operation 
                    data['column_name'].isnull()].index,axis=0)