Numpy Sort Function :

1.Ascending Order :

In [2]:
import numpy as np
a=np.array((1,2,54,34,6,21))
np.sort(a)

array([ 1,  2,  6, 21, 34, 54])

2.Descending Order :

sorted(a,reverse=True)

In [3]:
np.sort(a)[::-1]

array([54, 34, 21,  6,  2,  1])

3.Insert :

In [16]:
a=np.array((1,2,3,4,5))
print(a)
np.insert(a,2,100)

[1 2 3 4 5]


array([  1,   2, 100,   3,   4,   5])

4.Append()

In [18]:
a=np.array((1,2,3,4,5))
print(a)
np.append(10)

[1 2 3 4 5]


Append() :
   Apend the value str at the last index of the array. 

In [4]:
import numpy as np 

In [15]:
np.array([1,2,3,4])
np.append(a,8)

array([1, 2, 3, 4, 8])

In [17]:
#For Multidimensional Array    0=Row,1=Column
a=np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

For column wise append number of rows has to be same.
For row wise apend number of column has to be same.

In [8]:
b=np.arange(8).reshape(4,2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [18]:
np.append(a,b,axis=1)

array([[ 0,  1,  2,  3,  0,  1],
       [ 4,  5,  6,  7,  2,  3],
       [ 8,  9, 10, 11,  4,  5],
       [12, 13, 14, 15,  6,  7]])

In [23]:
a=np.arange(50).reshape(5,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [24]:
b=np.arange(40).reshape(5,8)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [25]:
np.append(a,b,axis=1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  0,  1,  2,  3,  4,  5,
         6,  7],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  8,  9, 10, 11, 12, 13,
        14, 15],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 16, 17, 18, 19, 20, 21,
        22, 23],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 24, 25, 26, 27, 28, 29,
        30, 31],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 32, 33, 34, 35, 36, 37,
        38, 39]])

Concatenate :
  Concatenate the arrays  along the axis :
1.Row-wise Concatenate :
    Number of column has to be same.
  Syntax :
    np.concatenate([array1,array2,axis=0])
2.Column-wise Concatenate :
    Number of row has to be same.
  Syntax :
    np.concatenate([array1,array2,axis=1])

In [35]:
#1.Row-wise Concatenate
array1=np.arange(16).reshape(4,4)
array2=np.arange(20).reshape(4,5)

In [37]:
a=np.concatenate([array1,array2],axis=1)
a

array([[ 0,  1,  2,  3,  0,  1,  2,  3,  4],
       [ 4,  5,  6,  7,  5,  6,  7,  8,  9],
       [ 8,  9, 10, 11, 10, 11, 12, 13, 14],
       [12, 13, 14, 15, 15, 16, 17, 18, 19]])

In [38]:
#2.Column-wise Concatenate
array1=np.arange(10).reshape(5,2)
array2=np.arange(12).reshape(6,2)

In [39]:
a=np.concatenate([array1,array2],axis=0)
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

Ceil() :
  It will yield out the maximum closet whole number to that decimal number.

In [42]:
a=10.2
np.ceil(a)

11.0

In [44]:
a=10.0
np.ceil(a)

10.0

Floor :
  It will yeild out the minimum closet number.

In [45]:
np.floor(10.9)

10.0

Around :
 Work extactly like around function for decimal part less than .5 it chooses minimum whole number otherwise closet maximum      number.

In [46]:
np.around(10.2)

10.0

In [49]:
np.around(10.7)

11.0

In [50]:
np.around(10.5)  #even

10.0

In [51]:
np.around(11.5)  #odd

12.0

Where :
  Syntax :
    np.where(condition, if meet, if does not meet)
    np.where(condition, true, false)

In [57]:
a=np.array([12,3,4,5,41,2])
a
np.where(a==41)

(array([4], dtype=int64),)

In [58]:
a=np.array([12,3,4,5,41,2])
a
np.where(a==41,100,a)

array([ 12,   3,   4,   5, 100,   2])

In [61]:
a=np.array(['Dhoni','Raina','Rohit','Virat'])
a
np.where(a=='Virat','Virat Kohli',a)

array(['Dhoni', 'Raina', 'Rohit', 'Virat Kohli'], dtype='<U11')

Argmax And Argmin:

In [65]:
a=np.array([1,20,4,52,423,424,2,80,54])
np.argmax(a),np.argmin(a)

(5, 0)

Size :

In [67]:
a=np.array([1,20,4,52,423,424,2,80,54])
np.size(a)

9

Min, Max, Sum, Mean, Average, Len, Standard Deviation, Variance :

In [68]:
#Min
np.min(a)

1

In [69]:
#Max
np.max(a)

424

In [71]:
#Mean
np.mean(a)

117.77777777777777

In [72]:
#Average
np.average(a)

117.77777777777777

In [74]:
#Standard Deviation
np.std(a)

165.42925831355478

In [77]:
#Variance
np.var(a)

27366.839506172837

Numpy Matrix :

1.Dot Matrix :

In [86]:
a=np.arange(10).reshape(5,2)
b=np.arange(16).reshape(2,8)
a,b
np.dot(a,b)

array([[  8,   9,  10,  11,  12,  13,  14,  15],
       [ 24,  29,  34,  39,  44,  49,  54,  59],
       [ 40,  49,  58,  67,  76,  85,  94, 103],
       [ 56,  69,  82,  95, 108, 121, 134, 147],
       [ 72,  89, 106, 123, 140, 157, 174, 191]])

2.Numpy Linear Algebra :

In [91]:
#3x+4y=15
#5x+6y=20
a=np.array([[3,4],[5,6]])
b=np.array([15,20])
a,b
np.linalg.solve(a,b)

array([-5. ,  7.5])

In [92]:
#Inverse Matrix
np.linalg.inv(a)

array([[-3. ,  2. ],
       [ 2.5, -1.5]])

In [94]:
#Eigen Matrix
np.linalg.eigvals(a)

array([-0.21699057,  9.21699057])

In [90]:
#Rank
np.linalg.matrix_rank(a)

2

Log Function :

In [78]:
np.log(10)

2.302585092994046

In [79]:
np.log10(10)

1.0

In [80]:
np.log(0)

C:\Users\Rudra Computer\AppData\Local\Temp\ipykernel_3144\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [81]:
#Expotential
np.exp(10)

22026.465794806718

In [82]:
np.exp(np.log10(10))

2.718281828459045

In [83]:
np.exp(1)

2.718281828459045

In [84]:
np.log2(1)

0.0

In [85]:
np.log2(2)

1.0

Trignometry Function :

In [95]:
np.pi

3.141592653589793

In [97]:
np.sin(np.pi/60)

0.05233595624294383

In [99]:
np.tan(np.pi/4)

0.9999999999999999

In [103]:
#Degree To Radian :
np.deg2rad(30),np.sin(0.5235987755982988)

(0.5235987755982988, 0.49999999999999994)

In [104]:
#Radian To Radian :
np.rad2deg(np.pi/30)

6.0

In [105]:
#Degrees
np.degrees(np.pi/6)

29.999999999999996

In [109]:
a=np.array([42,4,63,24,15,51,34,52,532])
np.bincount(a).argmax()

4